name: 'mtests'

on:
  push:
    branches:
    - temp9
  pull_request:
  schedule:
    - cron: '0 4 */1 * *' # At 04:00 on every day-of-month
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode: devel, nightly, testing, stable'
        default: 'devel'
        required: true
      publish:
        description: 'Publish to FTP: on - publish'
        default: 'off'
        required: false
  workflow_call:
    inputs:
      build_mode:
        description: 'Build mode: devel, nightly, testing, stable'
        default: 'devel'
        type: string
        required: true
      publish:
        description: 'Publish to FTP: on - publish'
        default: 'off'
        type: string

jobs:

  run_mtests:
    runs-on: ubuntu-22.04
    env:
        # Enable AddressSanitizer in the mtest build
        CFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
        CXXFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Free disk space
      run: |
        sudo docker system prune -a -f
        sudo rm -rf /usr/local/lib/android
    - name: Setup environment
      run: |
        bash ./build/ci/linux/setup.sh
    - name: Build
      run: |
        mkdir -p build.artifacts/env
        ./build/ci/linux/build.sh -n ${{ github.run_id }} --build_mode mtests
    - name: Run mtests
      run: |
        ./build/ci/linux/runmtests.sh
    - name: Upload artifacts on GitHub
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: mtestref
        path: ./build.debug/mtest
